name: omr
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip:
      - accelerate==1.9.0
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bidict==0.23.1
      - bleach==6.1.0
      - cachetools==5.5.2
      - cffi==1.17.1
      - chardet==5.2.0
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2024.9.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.25.1
      - google-api-python-client==2.179.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.70.0
      - h11==0.14.0
      - hf-xet==1.1.7
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.34.3
      - humdrum==0.7
      - ipykernel==6.29.5
      - ipython==8.27.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonargparse==4.40.2
      - jsonpickle==3.3.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - miditoolkit==1.0.1
      - mido==1.3.2
      - mistune==3.0.2
      - more-itertools==10.5.0
      - music21==9.1.0
      - muspy==0.5.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - opencv-python==4.12.0.88
      - overrides==7.7.0
      - packaging==23.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pdf2image==1.17.0
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - pretty-midi==0.2.10
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - proto-plus==1.26.1
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pypianoroll==1.0.4
      - python-json-logger==2.0.7
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.9.11
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - rsa==4.9.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - send2trash==1.8.3
      - sentence-transformers==3.1.1
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - setuptools-scm==8.1.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tokenizers==0.21.4
      - tomli==2.0.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.55
      - types-python-dateutil==2.9.0.20240906
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - wandb==0.18.2
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - x-transformers==1.25.10
      - pandas
